### ISSUE TITLE
Port forwarding through vagrant not set up

### ISSUE THREAD

**Issue by plusparth** [DRMF/operations-puppet-drmf#11]
It seems that in the new drmf2017 instance, port forwarding through vagrant is not set up. When I try to access localhost:8081 through curl on drmf2017, it does not connect to anything, while if I do the same in vagrant, it works fine.

**Comment by physikerwelt** [comment]
did you set it up
https://github.com/DRMF/operations-puppet-drmf/blob/master/setup.sh#L11
?

**Comment by physikerwelt** [comment]
@plato2000 unfortunately I do not have time to work on this issue.

**Comment by plusparth** [comment]
I have come back to working on this issue since I got the instance to actually work with the DRMF plugin (finally) 2 weeks ago. However, last week, I didn't get a chance to look at it because I was putting comments on pull requests and editing that. Today, when I tried to look at it, it didn't let me access the site even from Vagrant - I couldn't curl port 80 or 8080. Then, I tried to reprovision the machine, and it threw some error all the way at the beginning about node - then it didn't install anything and all of the dependencies failed. From what I remember, this is  the first time this has happened - it provisioned fine the first time and the error still happened. Also, in the Vagrant instance, Apache is running on port 80 and 8080 but doesn't allow any connections. At this point, I'm not sure what is causing this issue - can you take a look at it @physikerwelt ?

**Comment by physikerwelt** [comment]
which machine should I look at?

**Comment by plusparth** [comment]
@physikerwelt drmf2017

**Comment by plusparth** [comment]
@physikerwelt it seems that the wikidata role was not enabled - when I fixed that, it complains about some duplicate declaration:

```
==> default: Error: Duplicate declaration: Mediawiki::Import::Text[MediaWiki:Mainpage] is already declared in file /vagrant/puppet/modules/role/manifests/drmf.pp:139; cannot redeclare at /vagrant/puppet/modules/role/manifests/wikidata.pp:33 on node mediawiki-vagrant.dev
==> default: Error: Duplicate declaration: Mediawiki::Import::Text[MediaWiki:Mainpage] is already declared in file /vagrant/puppet/modules/role/manifests/drmf.pp:139; cannot redeclare at /vagrant/puppet/modules/role/manifests/wikidata.pp:33 on node mediawiki-vagrant.dev

```

But it doesn't have this issue on drmf2016, where the wikidata file is different.

When I copied the 2016 wikidata file over, I got the original error again.

**Comment by physikerwelt** [comment]
drmf2017 does not report any forwareded ports in addition to those defined in the roles

```
vagrant forward-port -l
Local port => VM's port
-----------------------
```

**Comment by physikerwelt** [comment]
I set up 8081 but even within the vagrant vm I don't get anything

```
vagrant@mediawiki-vagrant:~$ curl localhost:8081 -v
* Rebuilt URL to: localhost:8081/
* Hostname was NOT found in DNS cache
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8081 (#0)
> GET / HTTP/1.1
> User-Agent: curl/7.35.0
> Host: localhost:8081
> Accept: */*
>
< HTTP/1.1 404 Not Found
* Server Apache-Coyote/1.1 is not blacklisted
< Server: Apache-Coyote/1.1
< Content-Length: 0
< Date: Fri, 14 Oct 2016 23:03:02 GMT
<
* Connection #0 to host localhost left intact`
```

**Comment by physikerwelt** [comment]
Port forwarding in general works I tried using nc
