### ISSUE TITLE
Error with vagrant machine - can't find mediawiki

### ISSUE THREAD

**Issue by plusparth** [DRMF/operations-puppet-drmf#15]
It seems that MediaWiki isn't running. There are no issues related to this when provisioning the Vagrant machine, and the MySQL databases seem to be in place for the wikidata, Apache is running (on port 8080), and yet I can't actually get a webpage at that port - not even an error page. Before, it seemed like there were dependency errors in the vagrant provision process, but that doesn't seem to be applicable now. Even Mathosphere is running (but I haven't gotten a chance to test the search engine functionality).

@physikerwelt This is where I've been stuck for some time now - it seems now that it's not a provisioning issue or a port forwarding issue but maybe an issue with some role not enabled or something. Other than that, I don't really know where to go from here. I have not yet put in the real data from drmf2016, but I don't think that's the issue since I'm not even getting an error page.

**Comment by HowardCohl** [comment]
@physikerwelt Any comment on this?

**Comment by physikerwelt** [comment]
I have no idea what this problem is about.

> It seems that MediaWiki isn't running.

why not? I can see the wiki in my browser if I use ssh port forwarding to drmf2017.

**Comment by plusparth** [comment]
I have everything configured the same as it was for drmf2016 which works, and I can't see the wiki in the browser... Is there something else I have to configure that you have? Also, if I curl the page I don't get anything even from being sshed in through vagrant. I tried localhost:80, localhost:8080, and the same with /wiki and still no luck.

**Comment by plusparth** [comment]
@physikerwelt do you have any thoughts on this? I've been stuck here for a while

**Comment by plusparth** [comment]
So it seems that you have to look at /wiki/DRMF for it to show a page, but my issue was apparently that my drmf2017 forwarding to port 8080 didn't work (no idea why). I changed it to forward to a different port and now it works.
