### ISSUE TITLE
\binom macro does not render

### ISSUE THREAD

**Issue by physikerwelt** [DRMF/operations-puppet-drmf#4]
```
physikerwelt@drmf2016:/vagrant$ vagrant ssh

                 /
            .,. /
          ,mmmmn   ___  ___           _  _         _    _  _  _     _
  ,._   .,###"nI)  |  \/  |          | |(_)       | |  | |(_)| |   (_)
 # ###########     | .  . |  ___   __| | _   __ _ | |  | | _ | | __ _
 # ############""  | |\/| | / _ \ / _` || | / _` || |/\| || || |/ /| |
"  ####     #  ./  | |  | ||  __/| (_| || || (_| |\  /\  /| ||   < | |
   #'(#     #  "   \_|  |_/ \___| \__,_||_| \__,_| \/  \/ |_||_|\_\|_|
   #  ")     #
   #,  '"    '"

 * MediaWiki is located at /vagrant/mediawiki.
 * To interactively evaluate PHP and MediaWiki code, run 'hhvmsh'.
 * For a database shell, run 'mysql'.
 * To execute MediaWiki maintenance scripts, run 'mwscript ...'.
 * For help, visit https://www.mediawiki.org or #mediawiki on chat.freenode.net.

You have new mail.
Last login: Sat Mar  5 19:09:06 2016 from 10.0.3.1
vagrant@mediawiki-vagrant:~$ hhvmsh
Welcome to HipHop Debugger!
Type "help" or "?" for a complete list of commands.

Connecting to ::1:8089...
Attaching to vagrant's default sandbox and pre-loading, please wait...
::1> ^[[A^[[A^[[A^[[A
var_decho rray_diff() expects parameter 1 to be an array or collection in /vagrant/settings
echo rray_diff() expects parameter 1 to be an array or collection in /vagrant/settings
Notice: Attempted to interpret unknown debugger command as PHP!

Hit fatal : syntax error, unexpected T_STRING, expecting ',' or ';'
    #0 at [:1]
    #1 include(), called at [:1]

::1> var_dump($wgMathDefaultLaTeXMLSetting);
var_dump($wgMathDefaultLaTeXMLSetting);
array(9) {
  ["format"]=>
  string(5) "xhtml"
  ["whatsin"]=>
  string(4) "math"
  ["whatsout"]=>
  string(4) "math"
  [0]=>
  string(4) "pmml"
  [1]=>
  string(4) "cmml"
  [2]=>
  string(7) "mathtex"
  [3]=>
  string(18) "nodefaultresources"
  ["preload"]=>
  array(1) {
    [0]=>
    string(12) "DLMFmath.sty"
  }
  ["linelength"]=>
  int(90)
}
```

**Comment by physikerwelt** [comment]
```

physikerwelt@drmf:~$ hhvmsh
Welcome to HipHop Debugger!
Type "help" or "?" for a complete list of commands.

Connecting to ::1:8089...
Attaching to physikerwelt's default sandbox and pre-loading, please wait...
::1> var_dump($wgMathDefaultLaTeXMLSetting);
var_dump($wgMathDefaultLaTeXMLSetting);
array(8) {
  ["format"]=>
  string(5) "xhtml"
  ["whatsin"]=>
  string(4) "math"
  ["whatsout"]=>
  string(4) "math"
  [0]=>
  string(4) "pmml"
  [1]=>
  string(4) "cmml"
  [2]=>
  string(7) "mathtex"
  [3]=>
  string(18) "nodefaultresources"
  ["preload"]=>
  array(13) {
    [0]=>
    string(10) "LaTeX.pool"
    [1]=>
    string(11) "article.cls"
    [2]=>
    string(11) "amsmath.sty"
    [3]=>
    string(10) "amsthm.sty"
    [4]=>
    string(11) "amstext.sty"
    [5]=>
    string(11) "amssymb.sty"
    [6]=>
    string(9) "eucal.sty"
    [7]=>
    string(22) "[dvipsnames]xcolor.sty"
    [8]=>
    string(7) "url.sty"
    [9]=>
    string(12) "hyperref.sty"
    [10]=>
    string(16) "[ids]latexml.sty"
    [11]=>
    string(12) "DLMFmath.sty"
    [12]=>
    string(11) "forloop.sty"
  }
}
```

**Comment by HowardCohl** [comment]
@physikerwelt Does this solve the problem?

**Comment by physikerwelt** [comment]
yes see for example http://drmf2016.wmflabs.org/wiki/Definitions_and_Elementary_Properties

**Comment by HowardCohl** [comment]
That page doesn't have \binom in it.

**Comment by physikerwelt** [comment]
ah yes.. but \tfrac
here is an example with binom
http://drmf2016.wmflabs.org/w/index.php?title=Formula:ZE.ESUM.ESUM03
but there are new problem with macros I never saw before such as \terminant on
http://drmf2016.wmflabs.org/w/index.php?title=Formula:AS.RTSP.J

**Comment by HowardCohl** [comment]
Yes. Thanks!  How did you do it? What was wrong?

I will look into the \terminant issue. I think I might know what is going wrong.

**Comment by physikerwelt** [comment]
I changed the settings and defined the settings for the LaTeXML server absolutely cf. https://github.com/DRMF/operations-puppet-drmf/commit/b1b914cd686276200c7ad4d5a34a78e20a2cfd07 and not relatively to the default settings as it was done previously. For some reason the modification of the default settings does not work anymore.

**Comment by HowardCohl** [comment]
Regarding 

http://drmf2016.wmflabs.org/w/index.php?title=Formula:AS.RTSP.J

You've got other problems such as 

```
Bibliography

Equation in Section mula of KLS. 
```

If you had used ZETAtex2wiki.py you would have gotten the correct link to the formula in the DLMF.

**Comment by HowardCohl** [comment]
Ok For the `\terminant` problem, it looks like there was an old DLMFfcns.sty file on the LaTeXML server. I just uploaded a more recent one and restarted the LaTeXML apache.

**Comment by HowardCohl** [comment]
Purged cache on page...problem solved. :)

**Comment by HowardCohl** [comment]
Do you want me to purge the cache on the entire drmf2016 instance using the purging script?

**Comment by HowardCohl** [comment]
Concerning DLMF Chapter 25. In your new page:

http://drmf2016.wmflabs.org/wiki/Formula:ZE.ESUM.ESUM03

You have this 

```
Bibliography

Equation in Section mula of KLS. 
```

which corresponds to 

http://dlmf.nist.gov/25.16.E7

which is totally different than 

```
Bibliography

Equation (7), Section 25.16 of DLMF. 
```

which comes from

http://drmf.wmflabs.org/wiki/Formula:DLMF:25.16:E7

So I seriously doubt what you said about the mmd files (or the Wikitext) being the same

**Comment by physikerwelt** [comment]
@HowardCohl please try to create seperate issues for seperate problems
This repository https://github.com/DRMF/operations-puppet-drmf is about the puppet role that automatially sets up DRMF instances. With regard to the problem of the drmf2016 instance. This instance is currently work in progress, so to inspect it at the current stage does not make too much sense.
The mmd file I generated was on my local computer.
