### ISSUE TITLE
Puppet role fails without mathosphere

### ISSUE THREAD

**Issue by plusparth** [DRMF/operations-puppet-drmf#8]
I get this error: 

```
==> default: Error: Could not find class drmf::mathosphere for mediawiki-vagrant.dev on node mediawiki-vagrant.dev
==> default: Error: Could not find class drmf::mathosphere for mediawiki-vagrant.dev on node mediawiki-vagrant.dev
```

This is likely my mistake (probably didn't remove everything to do with mathosphere). I do not know if this is worth fixing since the mathosphere pull request is basically ready to merge at this point.

**Comment by physikerwelt** [comment]
merged

**Comment by physikerwelt** [comment]
maybe there is a way to run unit test for this repo. We should avoid by all means situations where the master branch does not work. [English corrected by @HowardCohl]
